### ISSUE TITLE
[Request] --dev/--debug argument for Dev Tools

### ISSUE THREAD

**Issue by joker-119** [ALEXWARELLC/tb_app#2]
Developer Tools should be disabled by default, however there should be a CLI argument to enable them.

**Comment by ALEXWARELLC** [comment]
Added `--dev-mode` switch.

**Comment by ALEXWARELLC** [comment]
Reopened due to error in switch not functioning correctly.

**Comment by ALEXWARELLC** [comment]
`--enable-devtools` is confirmed to work and will be used.
