### ISSUE TITLE
[BUG] Unable to download files

### ISSUE THREAD

**Issue by joker-119** [ALEXWARELLC/tb_app#8]
Trying to download a file from the app does not work.

**Comment by ALEXWARELLC** [comment]
A fix has been made but needs to be tested before it can be pushed to production 👍

**Comment by ALEXWARELLC** [comment]
Ok, so after some research, it appears that the API used isn't retrieving files as even after allowing the origin, it doesn't appear to even get the downloadable file.

Website:
![image](https://github.com/ALEXWARELLC/tb_app/assets/123724383/ac10d749-c4d7-438c-9f10-1c8d024dce33)

Terabit Desktop:
![image](https://github.com/ALEXWARELLC/tb_app/assets/123724383/6f0dd858-614e-442b-a211-e13d305e3c07)

**Comment by ALEXWARELLC** [comment]
A fix has been produced and will be built with the next revision release 👍

If you encounter any issues, feel free to reopen this issue or create a new one.
